### PR TITLE
Added git.build.time to get it available in the pre-build (for exampl…

### PR DESCRIPTION
**Pull request by dampfnudel**
…e for Sonarqube)

### CODE REVIEW

**Comment by pascalgn** [comment]
Thanks for the PR! Looks good to me, I have just a minor issue with the date format: `yyyyMMdd_HHmmss` is not totally common, so how about
- Change the format to ISO 8601 or
- Rename the property to something like `git.build.time.condensed` (though a better name would be preferred)

?

**Comment by dampfnudel** [comment]
Done. Due to the fact it should be used in a artifact I prefer to not use the ISO format

**Comment by pascalgn** [comment]
I might want to add separate properties `date` and `time`, so I think this combined one should be `datetime` really. Also, I think `condensed` is not much clearer than `simple`, so I would prefer the latter. So overall, the new property should be named `git.build.datetime.simple`. WDYT?

**Comment by pascalgn** [comment]
I have pushed the new version to Sonatype's repository, it should be in Central in a few minutes. Again, thanks for the PR! 👍

**Pull request merged**
